import type { Listing } from './types';

export const mockListings: Listing[] = [
  {
    id: 'lst-001',
    address: '421 Oak Street, Apt 2B',
    city: 'Milpitas',
    state: 'CA',
    rent: 1450,
    beds: 2,
    baths: 1,
    sqft: 820,
    accessibility: ['ground-floor', 'wide-doors', 'grab-bars'],
    programs: ['Section 8', 'LIHTC'],
    matchScore: 96,
    hasTour: true,
    tourId: 'tour-001',
    description: 'Spacious ground-floor 2BR with wide doorways and grab bars throughout. Quiet neighborhood, close to transit.',
    available: true,
  },
  {
    id: 'lst-002',
    address: '88 Calaveras Blvd, #310',
    city: 'Milpitas',
    state: 'CA',
    rent: 1200,
    beds: 1,
    baths: 1,
    sqft: 610,
    accessibility: ['elevator', 'wheelchair', 'hearing-loop'],
    programs: ['HUD', 'Section 8'],
    matchScore: 88,
    hasTour: false,
    description: 'ADA-compliant 1BR with elevator access and hearing loop in lobby. On-site laundry.',
    available: true,
  },
  {
    id: 'lst-003',
    address: '9 Montague Ave',
    city: 'San Jose',
    state: 'CA',
    rent: 1050,
    beds: 1,
    baths: 1,
    sqft: 550,
    accessibility: ['ground-floor'],
    programs: ['LIHTC'],
    matchScore: 82,
    hasTour: false,
    description: 'Cozy ground-floor studio converted to 1BR. Covered parking, pet friendly, minutes from VTA.',
    available: true,
  },
  {
    id: 'lst-004',
    address: '1200 Dixon Landing Rd, #44',
    city: 'Milpitas',
    state: 'CA',
    rent: 1800,
    beds: 3,
    baths: 2,
    sqft: 1100,
    accessibility: ['elevator', 'wheelchair', 'wide-doors', 'grab-bars'],
    programs: ['Section 8'],
    matchScore: 79,
    hasTour: false,
    description: 'Large 3BR fully wheelchair accessible. Elevator building, two assigned parking spots.',
    available: true,
  },
  {
    id: 'lst-005',
    address: '305 N Hillview Dr',
    city: 'Milpitas',
    state: 'CA',
    rent: 975,
    beds: 1,
    baths: 1,
    sqft: 490,
    accessibility: ['braille-signage', 'hearing-loop'],
    programs: ['HUD', 'LIHTC'],
    matchScore: 74,
    hasTour: false,
    description: 'Affordable 1BR in a deaf/low-vision friendly building. Braille signage, visual fire alerts.',
    available: true,
  },
  {
    id: 'lst-006',
    address: '701 Lundy Ave, Apt 6',
    city: 'San Jose',
    state: 'CA',
    rent: 1350,
    beds: 2,
    baths: 1,
    sqft: 740,
    accessibility: ['ground-floor', 'wide-doors'],
    programs: ['LIHTC'],
    matchScore: 70,
    hasTour: false,
    description: 'Corner 2BR on ground floor with extra windows. Wide hallways, close to schools and groceries.',
    available: false,
  },
  {
    id: 'lst-007',
    address: '233 S Abel St',
    city: 'Milpitas',
    state: 'CA',
    rent: 1150,
    beds: 1,
    baths: 1,
    sqft: 580,
    accessibility: ['elevator'],
    programs: ['Section 8'],
    matchScore: 65,
    hasTour: false,
    description: 'Clean 1BR with elevator access. Recently remodeled kitchen, on-site manager.',
    available: true,
  },
  {
    id: 'lst-008',
    address: '50 Ranch Drive, #12C',
    city: 'Milpitas',
    state: 'CA',
    rent: 1650,
    beds: 2,
    baths: 2,
    sqft: 950,
    accessibility: ['elevator', 'wheelchair', 'wide-doors', 'grab-bars', 'hearing-loop'],
    programs: ['HUD', 'Section 8', 'LIHTC'],
    matchScore: 91,
    hasTour: false,
    description: 'Fully accessible 2BR/2BA with comprehensive ADA features. Community garden, fitness center.',
    available: true,
  },
];
