import type { Listing } from './types';

export const mockListings: Listing[] = [
  // ── Milpitas ──────────────────────────────────────────────────────────────
  {
    id: 'lst-001',
    address: '421 Oak Street, Apt 2B',
    city: 'Milpitas', state: 'CA',
    rent: 1450, beds: 2, baths: 1, sqft: 820,
    accessibility: ['wheelchair', 'ground-floor', 'wide-doors', 'grab-bars'],
    programs: ['Section 8', 'LIHTC'],
    matchScore: 96, hasTour: true, tourId: 'tour-001',
    description: 'Spacious ground-floor 2BR with wide doorways and grab bars throughout. Quiet neighborhood, steps from Milpitas BART.',
    available: true,
  },
  {
    id: 'lst-002',
    address: '88 Calaveras Blvd, #310',
    city: 'Milpitas', state: 'CA',
    rent: 1200, beds: 1, baths: 1, sqft: 610,
    accessibility: ['elevator', 'wheelchair', 'hearing-loop'],
    programs: ['HUD', 'Section 8'],
    matchScore: 88,  hasTour: false,
    description: 'ADA-compliant 1BR with elevator access and hearing loop in lobby. On-site laundry, covered parking.',
    available: true,
  },
  {
    id: 'lst-007',
    address: '233 S Abel St, #4',
    city: 'Milpitas', state: 'CA',
    rent: 1150, beds: 1, baths: 1, sqft: 580,
    accessibility: ['elevator'],
    programs: ['Section 8'],
    matchScore: 75, hasTour: false,
    description: 'Clean 1BR with elevator access. Recently remodeled kitchen, on-site manager.',
    available: true,
  },
  {
    id: 'lst-004',
    address: '1200 Dixon Landing Rd, #44',
    city: 'Milpitas', state: 'CA',
    rent: 1800, beds: 3, baths: 2, sqft: 1100,
    accessibility: ['elevator', 'wheelchair', 'wide-doors', 'grab-bars'],
    programs: ['Section 8'],
    matchScore: 82, hasTour: true, tourId: 'tour-004',
    description: 'Large 3BR fully wheelchair accessible. Elevator building, two assigned parking, 0.4 mi to BART.',
    available: true,
  },
  {
    id: 'lst-005',
    address: '305 N Hillview Dr',
    city: 'Milpitas', state: 'CA',
    rent: 975, beds: 1, baths: 1, sqft: 490,
    accessibility: ['braille-signage', 'hearing-loop'],
    programs: ['HUD', 'LIHTC'],
    matchScore: 74, hasTour: false,
    description: 'Affordable 1BR in deaf/low-vision friendly building. Braille signage, visual fire alerts, TTY in lobby.',
    available: true,
  },
  {
    id: 'lst-008',
    address: '50 Ranch Drive, #12C',
    city: 'Milpitas', state: 'CA',
    rent: 1650, beds: 2, baths: 2, sqft: 950,
    accessibility: ['elevator', 'wheelchair', 'wide-doors', 'grab-bars', 'hearing-loop'],
    programs: ['HUD', 'Section 8', 'LIHTC'],
    matchScore: 91, hasTour: true, tourId: 'tour-002',
    description: 'Fully accessible 2BR/2BA with comprehensive ADA features. Community garden, fitness center, on-site management.',
    available: true,
  },
  {
    id: 'lst-009',
    address: '670 Bellew Dr, Apt 1',
    city: 'Milpitas', state: 'CA',
    rent: 1095, beds: 1, baths: 1, sqft: 540,
    accessibility: ['ground-floor'],
    programs: ['LIHTC'],
    matchScore: 70, hasTour: false,
    description: 'Garden-level 1BR in quiet complex. Patio, storage unit, pet-friendly, near Great Mall.',
    available: true,
  },
  {
    id: 'lst-010',
    address: '177 Tarob Ct',
    city: 'Milpitas', state: 'CA',
    rent: 1375, beds: 2, baths: 1, sqft: 780,
    accessibility: ['ground-floor', 'wide-doors'],
    programs: ['Section 8', 'LIHTC'],
    matchScore: 85, hasTour: false,
    description: 'Updated 2BR on ground floor. New appliances, covered carport, laundry in unit. Walk Score: 72.',
    available: true,
  },
  {
    id: 'lst-011',
    address: '500 S Milpitas Blvd, #205',
    city: 'Milpitas', state: 'CA',
    rent: 1280, beds: 1, baths: 1, sqft: 625,
    accessibility: ['elevator', 'wheelchair'],
    programs: ['HUD'],
    matchScore: 79, hasTour: false,
    description: 'Bright 1BR with roll-in shower and elevator. Near Costco, VTA bus line. Income-restricted.',
    available: false,
  },

  // ── San Jose ──────────────────────────────────────────────────────────────
  {
    id: 'lst-003',
    address: '9 Montague Ave, Unit A',
    city: 'San Jose', state: 'CA',
    rent: 1050, beds: 1, baths: 1, sqft: 550,
    accessibility: ['ground-floor'],
    programs: ['LIHTC'],
    matchScore: 78, hasTour: false,
    description: 'Cozy ground-floor 1BR, converted from large studio. Covered parking, 5 min to VTA light rail.',
    available: true,
  },
  {
    id: 'lst-006',
    address: '701 Lundy Ave, Apt 6',
    city: 'San Jose', state: 'CA',
    rent: 1350, beds: 2, baths: 1, sqft: 740,
    accessibility: ['ground-floor', 'wide-doors'],
    programs: ['LIHTC'],
    matchScore: 68, hasTour: false,
    description: 'Corner 2BR on ground floor with extra windows. Wide hallways, close to schools and groceries.',
    available: false,
  },
  {
    id: 'lst-012',
    address: '2050 Alum Rock Ave, #8',
    city: 'San Jose', state: 'CA',
    rent: 1125, beds: 1, baths: 1, sqft: 570,
    accessibility: ['elevator', 'ground-floor'],
    programs: ['Section 8', 'HUD'],
    matchScore: 80, hasTour: false,
    description: 'Renovated 1BR in secure building. On-site laundry, small gym, near 680 freeway. Walk Score: 80.',
    available: true,
  },
  {
    id: 'lst-013',
    address: '1475 Foxworthy Ave',
    city: 'San Jose', state: 'CA',
    rent: 1595, beds: 2, baths: 2, sqft: 890,
    accessibility: ['elevator', 'wheelchair', 'grab-bars'],
    programs: ['Section 8', 'LIHTC'],
    matchScore: 86, hasTour: true, tourId: 'tour-003',
    description: 'Fully accessible 2BR/2BA. Each bedroom has en-suite grab bars. Pool, BBQ, gated parking.',
    available: true,
  },
  {
    id: 'lst-014',
    address: '3250 Story Rd, #112',
    city: 'San Jose', state: 'CA',
    rent: 925, beds: 0, baths: 1, sqft: 420,
    accessibility: ['elevator'],
    programs: ['LIHTC', 'HUD'],
    matchScore: 65, hasTour: false,
    description: 'Studio with Murphy bed, updated kitchen. Income-restricted, income verification required. Transit Score: 91.',
    available: true,
  },
  {
    id: 'lst-015',
    address: '880 S 10th St, #4B',
    city: 'San Jose', state: 'CA',
    rent: 1450, beds: 2, baths: 1, sqft: 760,
    accessibility: ['ground-floor', 'wide-doors', 'grab-bars'],
    programs: ['Section 8'],
    matchScore: 77, hasTour: false,
    description: 'Ground floor 2BR in SJ downtown adjacent. Wide doorways, roll-under kitchen sink, 10 min to SAP Center.',
    available: true,
  },

  // ── Santa Clara ───────────────────────────────────────────────────────────
  {
    id: 'lst-016',
    address: '2700 Augustine Dr, #3',
    city: 'Santa Clara', state: 'CA',
    rent: 1550, beds: 2, baths: 1, sqft: 800,
    accessibility: ['elevator', 'wheelchair'],
    programs: ['Section 8', 'LIHTC'],
    matchScore: 83, hasTour: false,
    description: 'Spacious 2BR near Apple Campus. ADA-compliant building, pool, covered parking. Income-restricted.',
    available: true,
  },
  {
    id: 'lst-017',
    address: '445 Lafayette St',
    city: 'Santa Clara', state: 'CA',
    rent: 1175, beds: 1, baths: 1, sqft: 600,
    accessibility: ['ground-floor'],
    programs: ['LIHTC'],
    matchScore: 72, hasTour: false,
    description: 'Charming 1BR in historic building, ground floor. Original hardwood, updated bath. Walk to Caltrain.',
    available: true,
  },

  // ── Fremont ───────────────────────────────────────────────────────────────
  {
    id: 'lst-018',
    address: '39888 Mission Blvd, #7',
    city: 'Fremont', state: 'CA',
    rent: 1300, beds: 2, baths: 1, sqft: 750,
    accessibility: ['elevator', 'wheelchair', 'hearing-loop'],
    programs: ['HUD', 'Section 8'],
    matchScore: 81, hasTour: false,
    description: 'Two-level 2BR in accessible building. Hearing loop in community room, near BART, large storage.',
    available: true,
  },
  {
    id: 'lst-019',
    address: '4480 Peralta Blvd, #22',
    city: 'Fremont', state: 'CA',
    rent: 1075, beds: 1, baths: 1, sqft: 520,
    accessibility: ['ground-floor', 'wide-doors'],
    programs: ['LIHTC'],
    matchScore: 69, hasTour: false,
    description: 'Quiet 1BR on ground floor in established complex. Wide entrance, washer/dryer hookups, carport.',
    available: true,
  },
  {
    id: 'lst-020',
    address: '37000 Cedar Blvd, #305',
    city: 'Fremont', state: 'CA',
    rent: 1725, beds: 3, baths: 2, sqft: 1050,
    accessibility: ['elevator', 'wheelchair', 'wide-doors', 'grab-bars', 'braille-signage'],
    programs: ['HUD', 'Section 8', 'LIHTC'],
    matchScore: 90, hasTour: true, tourId: 'tour-005',
    description: 'Rare fully-accessible 3BR with braille signage. Community is deaf/blind friendly. 3 blocks to BART.',
    available: true,
  },
];
